### ISSUE TITLE
Use Yeelight BLE gateway?

### ISSUE THREAD

**Issue by thatso** [AlCalzone/ioBroker.ble#111]
Not sure if this idea is better suited here or at the [Yeelight addon](https://github.com/cahek2202/ioBroker.yeelight/issues/9) ... that's why I'm asking both projects:
most of the Yeelight ceiling lights and the bedside lamp include a BLE gateway to connect to BLE enabled sensors like the thermo-/hygrometer to extend their otherwise limited BLE range over WLAN.
The MiHome app uses this functionality to make sensors readable even if the mobile phone is not in the BLE proximity.
Do you have any plans to make this functionality available in iobroker?

**Comment by AlCalzone** [comment]
The connection to the gateway is over WLAN, so connecting to it would fall outside the scope of this adapter. I think this is better suited in the yeelight adapter.
