### ISSUE TITLE
Xiaomi/ClearGrass CGG1 already included?

### ISSUE THREAD

**Issue by thatso** [AlCalzone/ioBroker.ble#135]
Your current changelog reads:

> 0.7.3 (2019-04-05)
>    (AlCalzone) Add MiTemperature watch with E-Ink display

Is this about the new Xiaomi/ClearGrass BLE thermometer and hygrometer CGG1 or something completely different?
![image](https://ae01.alicdn.com/kf/HTB1INcDMCzqK1RjSZFpq6ykSXXal/xiaomi-mijia-Digital-Bluetooth-Thermometer-and-Hygrometer-Electronic-Ink-Screen-30-Days-Data-Automatic-Recording-By.jpg)

**Comment by AlCalzone** [comment]
I can't say for sure. This looks like the device, but I don't have any myself. I am just working with the information I get from the forum or issues here. If it is not working, I probably just need to add another MAC prefix to the detection logic.

**Comment by MarcoLaser** [comment]
Das Gerät oben wird schon länger unterstützt. Klappt auch, habe ich selbst im Einsatz. Das Gerät aus dem Changelog müsste das hier sein : [https://de.aliexpress.com/item/32996877374.html?spm=a2g0o.productlist.0.0.42c57ffbcsEhxC&algo_pvid=58ca35cb-5112-4e4d-b372-e5e9043f8b3c&algo_expid=58ca35cb-5112-4e4d-b372-e5e9043f8b3c-12&btsid=65818fff-6c70-454f-a103-05d37761ae00&ws_ab_test=searchweb0_0%2Csearchweb201602_5%2Csearchweb201603_53](url)

Das habe ich seit gestern im Einsatz jedoch sind die Werte nicht zu verwenden. Es wird nur angezeigt fe95 mit dem Wert : 70205b0478281061c8593f090610027602 . Hoffe das Hilft dir weiter. Falls du noch was brauchst kann ich dir auch gern weiterhelfen. Danke für die ganze Arbeit, weiter so !

**Comment by AlCalzone** [comment]
> Das habe ich seit gestern im Einsatz jedoch sind die Werte nicht zu verwenden. Es wird nur angezeigt fe95 mit dem Wert : 70205b0478281061c8593f090610027602 . Hoffe das Hilft dir weiter.

Kannst du mir grade die Mac-Adresse deines Geräts durchgeben?

**Comment by MarcoLaser** [comment]
Müsste das sein ne? ble.0.3f:59:c8:61:10:28

**Comment by AlCalzone** [comment]
> 3f:59:c8

Das ist auch schon im Adapter hinterlegt. Welche Version hast du installiert? Falls sie aktuell ist, benötige ich Debug-Ausgaben (Adapter auf Loglevel "debug") stellen.

**Comment by MarcoLaser** [comment]
Hab Version 0.7.2

**Comment by MarcoLaser** [comment]
https://pastebin.com/WqbW7mYY Hoffe das hilft dir weiter.

**Comment by AlCalzone** [comment]
Na da kann ich lange nach dem Fehler suchen 😓 
Das Gerät wird erst ab Version 0.7.3 unterstützt.

**Comment by MarcoLaser** [comment]
Die gibt's aber noch nicht im ioBroker direkt oder? Naja ich schau dann mal
wo ich die latest her bekomme

AlCalzone <notifications@github.com> schrieb am Di., 30. Juli 2019, 20:57:

**Comment by AlCalzone** [comment]
Wenn du dein Repo auf Stable stehen hast, möglicherweise nicht.
Du kannst aktualisieren mit
```
cd /opt/iobroker
npm i iobroker.ble
iobroker upload ble
```

**Comment by MarcoLaser** [comment]
Super Danke, jetzt klappts :)

**Comment by thatso** [comment]
> Das Gerät oben wird schon länger unterstützt. Klappt auch, habe ich selbst im Einsatz.

Glaube ich nicht. Ich bin mir sicher, Du verwechselt das mit dem Vorläufer. Der hat ein LCD Display und eine AAA Batterie. Das von mir oben genannte Modell kam ganz neu heraus, hat E-Ink und eine Knopfzelle.

**Comment by AlCalzone** [comment]
@thatso
Ich vermute mit hoher Zuversicht dass das Gerät auch unterstützt wird. Möglicherweise muss ich aber die BLE Mac Adresse im Adapter hinterlegen, dass statt fe95 lesbare Werte angezeigt werden.

**Comment by AlCalzone** [comment]
Mit einer der neueren Versionen wird nicht mehr nach MAC-Adresse gefiltert, sondern einmalig versucht, eine Nachricht zu dekodieren. Damit sollten alle zukünftigen Geräte verfügbar sein, sofern keine Änderung am Protokoll aufgetreten ist.
