### ISSUE TITLE
Remove admin dependency

### ISSUE THREAD

**Issue by cburghardt** [AlCalzone/ioBroker.ble#147]
Currently the ble adapter depends on the admin adapter to be present on the same host which is not the case for master/slave. I understand this dependency can be removed in the adapter. This would be great as I am currently running several ble instances and as such "dead" admin nodes.

**Comment by AlCalzone** [comment]
See: https://github.com/AlCalzone/ioBroker.ble/pull/128
Already merged, not yet released
