### ISSUE TITLE
New version of ble Adapter raises ping on raspberry zero slave host

### ISSUE THREAD

**Issue by nob0dy80** [AlCalzone/ioBroker.ble#158]
Hi,

after a upgrade due the new version doesnt need admin host i got a really strange behavior on the raspberry zero w.
Using this one as slave only for the ble and zigbee adapter.

ble running:
![image](https://user-images.githubusercontent.com/28686079/61587752-4bfca680-ab90-11e9-98b1-6e7ace78e3a7.png)

ble stopped:
![image](https://user-images.githubusercontent.com/28686079/61587756-66cf1b00-ab90-11e9-9d53-c9c4de33016c.png)

Any explaination for that?

**Comment by AlCalzone** [comment]
To be honest, I have no clue. If anyone finds out why, please let me know.

**Comment by nob0dy80** [comment]
@AlCalzone 
Well at first, i can say it is not CPU or RAM.

without ble
18:23:40 up 3 days,  3:37,  1 user,  load average: 0,12, 0,13, 0,16

with ble
18:32:50 up 3 days,  3:46,  1 user,  load average: 0,33, 0,25, 0,20

even ble doubles the cpu load, there is enough space left.

i guess, it is the BUS. i think  wlan and bluetooth are handled over the same BUS on the pi zero.
due the ble adapter is always listening and causing a high data exchange (not in size but in 
continuity) it slows down the response times.
i guess its like when you ping a website and start a multisegment download on your client with full speed. the pings raise in that case too.

but its speculative

**Comment by nob0dy80** [comment]
Asked in a german-spoken raspberry forum.
https://forum-raspberrypi.de/forum/thread/43800-raspi-zero-w-ping-verzehnfacht-sich-bei-bluetoothnutzung/

lets see what happens.

**Comment by nob0dy80** [comment]
@AlCalzone 
Reason is there is only one chip that handles bluetooth and wlan... and they are sharing one antenne. that is the reason.
Closing this issue cause it has nothing to do with BLE Adapter.
