### ISSUE TITLE
Very infrequent data

### ISSUE THREAD

**Issue by lug-gh** [AlCalzone/ioBroker.ble#171]
**Describe the bug**  
My sensor rarely delivers data, and I don't know why.
The signal should not be the problem, iobroker and sensor are about 1m apart.
I set the log to silly, so I see that it doesn't seem to pull any data at all.

I did execute ``setcap cap_net_raw+eip $(eval readlink -f `which node`)`` but it didn't help.
Also the instance has a green dot, so I assume it should be fine.
The data is transmitted via app every second. And yes, I removed the sensor from the app before using iobroker, stopped it and turned off Bluetooth on my mobile phone.

**Screenshots & Logfiles**  

ble.0 | 2019-08-09 20:00:04.863 | debug | serviceData = []
-- | -- | -- | --
ble.0 | 2019-08-09 20:00:04.863 | debug | has serviceData: true
ble.0 | 2019-08-09 20:00:04.863 | debug | has advertisement: true
ble.0 | 2019-08-09 20:00:04.861 | debug | discovered peripheral 78:c3:46:da:72:39

![image](https://user-images.githubusercontent.com/24546639/62799403-ffe2b900-bae0-11e9-90d9-4865324f0643.png)
![image](https://user-images.githubusercontent.com/24546639/62799430-12f58900-bae1-11e9-825e-7bee247328fa.png)

**Versions:**  
 - Adapter version: 0.8.1
 - JS-Controller version: 1.4.2
 - Node version: v8.16.0
 - Operating system: Ubuntu 18.04.2 LTS

**Comment by AlCalzone** [comment]
Unauthorized means that the BLE process may not access the bluetooth device. Your setcap command seems incomplete:
```
sudo setcap 'cap_net_admin,cap_net_bind_service,cap_net_raw+eip' $(eval readlink -f `which node`)
```
should be correct.

**Comment by lug-gh** [comment]
![image](https://user-images.githubusercontent.com/24546639/62821699-4f74c380-bb79-11e9-904c-5c134cd11660.png)
I did not change anything yet, but today it looks like this. But still no new data

**Comment by lug-gh** [comment]
It's probably the signal after all. If I place the sensor right next to my iobroker, it works fine. Damn it.
