### ISSUE TITLE
Wrong data for Xiaomi temperature sensor

### ISSUE THREAD

**Issue by JonasR-** [AlCalzone/ioBroker.ble#18]
![image](https://user-images.githubusercontent.com/4939798/37955104-ef1bf474-31a7-11e8-86f2-537d7e86696d.png)

I guess 14489 °C is too high :D Also the humidity jumps from 19 to 56 and back again

serviceData = [{"uuid":"fe95","data":{"type":"Buffer","data":[80,32,170,1,202,232,2,210,168,101,76,13,16,4,195,0,54,2]}},{"uuid":"ffff","data":{"type":"Buffer","data":[219,128,28,255,144,191]}}]

serviceData = [{"uuid":"fe95","data":{"type":"Buffer","data":[80,32,170,1,201,232,2,210,168,101,76,13,16,4,197,0,53,2]}},{"uuid":"ffff","data":{"type":"Buffer","data":[219,128,28,255,144,191]}}]

serviceData = [{"uuid":"fe95","data":{"type":"Buffer","data":[80,32,170,1,200,232,2,210,168,101,76,10,16,1,100]}},{"uuid":"ffff","data":{"type":"Buffer","data":[219,128,28,255,144,191]}}]

serviceData = [{"uuid":"fe95","data":{"type":"Buffer","data":[80,32,170,1,199,232,2,210,168,101,76,6,16,2,54,2]}},{"uuid":"ffff","data":{"type":"Buffer","data":[219,128,28,255,144,191]}}]

**Comment by AlCalzone** [comment]
Yeah, 14489 sounds a bit high... I'll check it out, thanks for the raw data!

**Comment by JonasR-** [comment]
No problem :) 
The sensor does not send the same amount of data everytime, I guess thats the cause of the wrong object data

**Comment by JonasR-** [comment]
0.4.2 works for me :)

![image](https://user-images.githubusercontent.com/4939798/37960281-8e585ec6-31b5-11e8-9277-06bcb81e3922.png)

**Comment by AlCalzone** [comment]
> The sensor does not send the same amount of data everytime, I guess thats the cause of the wrong object data

The amount of data depends on the type of data the packet contains. Your problem simply came from wrong information I had with no sensor to test. The sensor sends 3 or 4 types of packets:
* battery
* humidity
* temperature and humidity
* (and maybe temperature)

The combined one was supposed to contain 1+1 bytes, but it contains 2+2 bytes.

**Comment by JonasR-** [comment]
Okay, thanks for your work :)
