### ISSUE TITLE
Xiaomi Mosqito repellent status flags?

### ISSUE THREAD

**Issue by Ilovegym66** [AlCalzone/ioBroker.ble#181]
I've since some days a xiaomi mosqito repellent installed, looked nice, the adapter recognize it, but only the battery flag was shown, see picture below.

![Screenshot_2019-08-16 objects - ioBroker](https://user-images.githubusercontent.com/36229898/63168461-81cc6800-c034-11e9-94ba-841ec8df9c58.png)

**Comment by AlCalzone** [comment]
Hmm, there should at least be values displayed.
