### ISSUE TITLE
Can't connect to driver anymore after apt-get upgrade.

### ISSUE THREAD

**Issue by cataclisma** [AlCalzone/ioBroker.ble#241]
This morning I did a apt-get upgrade.
Since the upgrade, The ble Adapter can't connect to the driver anymore. It worked perfectly for months but now the "driverState" says "unkonown".
I reinstalled the complete adapter and updated to latest verison instead of stable version but nothin helped.

The packages which were updated via apt-get were:
libmagic1:armhf (1:5.35-4, 1:5.35-4+deb10u1), libmagic-mgc:armhf (1:5.35-4, 1:5.35-4+deb10u1), file:armhf (1:5.35-4, 1:5.35-4+deb10u1)

**Comment by AlCalzone** [comment]
Have you tried running the iobroker fixer?

**Comment by cataclisma** [comment]
What is the iobroker fixer?

Maybe it was also the upgrade from thursday, but I'm sure it worked at least last Friday.
The changes from Thursday were:
Install: linux-base:armhf (4.6, automatic), libklibc:armhf (2.0.6-1+rpi1, automatic), busybox:armhf (1:1.30.1-4, automatic), pigz:armhf (2.4-1, automatic), klibc-utils:armhf (2.0.6-1+r$
Upgrade: raspi-config:armhf (20191008, 20191021), nodejs:armhf (10.16.3-1nodesource1, 10.17.0-1nodesource1)

I tried to restore a backup from the backitup adapter but it didn't helped.

**Comment by cataclisma** [comment]
OK, I used the iobroker fixer.
Now the ble adapter can connect to the driver again!
But, now all my devices (xiaomi ble devices) are gone and the don't show up in the ble object.
Do you have an idea how I could solve this?

Thank you for the support!

**Comment by cataclisma** [comment]
I had to do a full restore. Now it works everything fine.
This was strange! But thanks anyway.

**Comment by AlCalzone** [comment]
Whenever you do a nodejs update, the permissions to access some ports and hardware (including Bluetooth) are lost. The fixer repairs those permissions.
