### ISSUE TITLE
Can't start adapter on Slave

### ISSUE THREAD

**Issue by Anzic23** [AlCalzone/ioBroker.ble#245]
installed the adapter on the slave system. The hciconfig hciX command returns an error:
Can't open HCI socket.: Address family not supported by protocol
maybe with a command something wrong? could you tell me the right one.
Main HOST:
JS-Controller 2.0.39
Node.js v10.17.0
NPM 6.11.3
slave HOST:
Raspberry pi 3b+
JS-Controller 2.0.39
Node.js v10.17.0
NPM 6.11.3

**Comment by AlCalzone** [comment]
Have you installed all the prerequisites?
https://github.com/AlCalzone/ioBroker.ble#installation

**Comment by Anzic23** [comment]
Yes

**Comment by Anzic23** [comment]
in the DietPi image has been disabled Bluetooth. After switching on, installing `sudo apt-get install bluetooth bluez blueman` and rebooting Raspberry pi 3 b+, the adapter start working.

**Comment by Anzic23** [comment]
probably install a Bluetooth bluez blueman didn't need to. May be turn on Bluetooth and reboot it this is the solution.
