### ISSUE TITLE
ble adapter found 29.456 devices?!?

### ISSUE THREAD

**Issue by rehmosch** [AlCalzone/ioBroker.ble#268]
Hey,

thank you for this great adapter ;)

I live in Munich City and my ble adapter find about 29.456 devices and my RP4 is lagging. The most devices are from Uber and Tier Scooters, Cars, Smart-Watches, Bose Sound  ....

But i would like to know, how the ble adapter scans only my xiaomi (Miija Temperature & Humidity Sensors)? Thank you ;)

**Comment by AlCalzone** [comment]
1. Disable the option "Allow creation of devices without advertised data"
2. Only enter `xiaomi` in the option "Monitored services, * for all services"
3. Change the state "options.allowNewDevices" to `false` after all your devices have been detected

**Comment by rehmosch** [comment]
Sorry, i forgot to answer you. Yep is fixed. 
Thank AlCalzone ;)
