### ISSUE TITLE
Add an option to stop recording unknown devices

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/ioBroker.ble#27]
Based on #26 there should be an option to stop recording or ignore unknown devices.

**Comment by Ilovegym66** [comment]
or a possibility to filter names / mac addresses?

**Comment by cimba007** [comment]
After running the adapter for one day I got 150+ devices in my list. I can only assume that some devices randomize their mac-address.

**Comment by cimba007** [comment]
@AlCalzone Any progress on this? I got like 7000states after 1week and iobroker becomes just slow and unresponsive.

**Comment by cimba007** [comment]
@AlCalzone Maybe it is easyer to just just add a simple switch "allow new devices / disallow new devices."

**Comment by AlCalzone** [comment]
Fixed in c4c759c

**Comment by cimba007** [comment]
@AlCalzone: I now get 

ble.0 | 2018-12-24 01:58:05.721 | error | unhandled promise rejection: Error: Cannot find module '@abandonware/bluetooth-hci-socket'
-- | -- | -- | --

**Comment by AlCalzone** [comment]
Yep, you need to install all ioBroker-related npm modules inside `/opt/iobroker`. Otherwise you'll get duplicate modules lying around somewhere where you don't need them.

Also you should take a look at this regarding `sudo` and `npm`:
https://forum.iobroker.net/viewtopic.php?f=8&t=19209
Or (in english) http://hood.ie/blog/why-you-shouldnt-use-sudo-with-npm.html (last paragraph).

You most likely messed up your permissions before, so the installation failed.

**Comment by cimba007** [comment]
@AlCalzone Sorry to bother you again .. it seems I restored an backup which did not have yet the "stop recording of unknown devices" flag set .. and I forgot and now out of my 11302 states 10300 are from BLE. The Objectview is just crowded and I don't know how to delete all states without a name .. or even delete all states that have not been updated for a longer period of time.

Do you have any idea on how to do this beside deleting all BLE states together?

**Comment by AlCalzone** [comment]
> Do you have any idea on how to do this beside deleting all BLE states together?

I guess that is the easiest solution. Otherwise, you could write a script that selects all BLE states, filters them by `obj.ts` (last update timestamp) and deletes all the states where the timestamp is older than a certain date.

**Comment by cimba007** [comment]
You can't access adapter states from script .. so .. btw:

![image](https://user-images.githubusercontent.com/3453121/54715985-ffa74880-4b54-11e9-9459-da1cf20fb28a.png)

This totally bricked my raspberry pi .. had to delete ble from console .. currently no way to recover except deleting ble
