### ISSUE TITLE
Xiaomi Sensoren liefern keine Werte

### ISSUE THREAD

**Issue by erklaerbaer1** [AlCalzone/ioBroker.ble#299]
Hallo,

erstmal vielen Dank für die geleistete Arbeit an dem Adapter.

Ich frage hier nur  der Vollständigkeit halber. Ich habe versucht die quadratischen Xiaomi Temperatursensoren anzubindnen. Eine Ankopplung funktionierte umgehend. Allerdings liefern diese keine Werte . 

Ich vermute mal das "nur" die runden unterstützt werden ?

Vielen Dank

![grafik](https://user-images.githubusercontent.com/59808248/72226832-c0d7f880-3595-11ea-99bd-126684792c89.png)

**Comment by AlCalzone** [comment]
Ja, leider senden die quadratischen nicht von sich aus die Messwerte, wie die anderen Geräte es tun.

**Comment by erklaerbaer1** [comment]
Danke...! 🙂

AlCalzone <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 08:11:
