### ISSUE TITLE
Mi Flower - The device is not fully initialized.

### ISSUE THREAD

**Issue by BuZZy1337** [AlCalzone/ioBroker.ble#33]
I always get the message that my Mi Flora is not fully initialized?
But i get all the values via the Flowercare app on my phone..
I switched off the Bluetooth on my phone to be sure that there is no connection problem..

But i keep getting this message - and no values in ioBroker?

ble.0 | 2018-10-27 17:09:43.227 | debug | xiaomi >> Use its app to complete the initialization.
-- | -- | -- | --
ble.0 | 2018-10-27 17:09:43.227 | debug | xiaomi >> The device is not fully initialized.
ble.0 | 2018-10-27 17:09:43.227 | debug | xiaomi >> got data: 31029800071d0e678d7cc40d
ble.0 | 2018-10-27 17:09:43.225 | debug | updating rssi state for c4:7c:8d:67:0e:1d
ble.0 | 2018-10-27 17:09:43.223 | debug | plugin mi-flora is handling c4:7c:8d:67:0e:1d
ble.0 | 2018-10-27 17:09:43.223 | debug | serviceData = [{"uuid":"fe95","data":{"type":"Buffer","data":[49,2,152,0,7,29,14,103,141,124,196,13]}}]
ble.0 | 2018-10-27 17:09:43.223 | debug | has serviceData: true
ble.0 | 2018-10-27 17:09:43.223 | debug | has advertisement: true
ble.0 | 2018-10-27 17:09:43.223 | debug | discovered peripheral c4:7c:8d:67:0e:1d

**Comment by AlCalzone** [comment]
`31029800071d0e678d7cc40d` is indeed an incomplete packet without any measurements. The app connects actively to the sensor and requests the data, the adapter just listens for the sensor to broadcast it. 

There might be a firmware update for the sensor that needs to be done befor it starts broadcasting.

**Comment by BuZZy1337** [comment]
Hm shit.. Guess the problem is that I bought the international version of the sensor.. Firmware is 2.7.0.. And there is no update available..

**Comment by AlCalzone** [comment]
You could ask in the forum thread. I only have one sensor and that one is working ;)
