### ISSUE TITLE
Names of Flowers are delete and not changeable

### ISSUE THREAD

**Issue by Ilovegym66** [AlCalzone/ioBroker.ble#34]
Hi, with Version 0.5.3 the names of the flowers I had given in the past are now away.. and I can't change the name of a sensor .. 
npm 6.4.1, node 8.12, raspberry 3, raspberian kernel 4.14.71
iobroker admin 3.5.10, js-controller 1.4.2

**Comment by AlCalzone** [comment]
Hmmm I thought I had fixed that. I need to check it again.

**Comment by AlCalzone** [comment]
Fixed in v0.5.4
