### ISSUE TITLE
Add support for Xiaomi Mijia Temp & Humidity Sensor 2 (LYWSD03MMC )

### ISSUE THREAD

**Issue by Alex-Ga** [AlCalzone/ioBroker.ble#352]
There is a project which sends the data via mqtt (as a callback).

https://github.com/JsBergbau/MiTemperature2

It should be noticed, that the Mi Home App connects to the Device and sets it into a "connected sleep mode" after reading the values.

They managed to reverse engineer this power saveing message.

Would be great to build something to the iobroker adapter. 

If you have only those Mijia BLE Devices or another spare RasPi you could send it to the mqtt server with this project outside the iobroker, but integrating into your module would be great. I have 4 sensors and measure equipment for beta testing ;-)

**Comment by AlCalzone** [comment]
https://github.com/atc1441/ATC_MiThermometer

**Comment by blackrozes** [comment]
The custom firmware it works very good for me for some day
![image](https://user-images.githubusercontent.com/25933118/94416535-4250d480-017f-11eb-89b0-ac7c8e8e63c7.png)

**Comment by kaesglocke** [comment]
> The custom firmware it works very good for me since some days
> ![image](https://user-images.githubusercontent.com/25933118/94416535-4250d480-017f-11eb-89b0-ac7c8e8e63c7.png)

Hello blackrozes,
I install the Custom Firmware, but I do not see the data like yours in the picture. My Data looks like this.

![image](https://user-images.githubusercontent.com/72124824/94653512-f7a89700-02fb-11eb-9f59-2404c1df2729.png)

I think you program a custom plugin ist this correct?
Can you tell me what you are doing to become the correct Data.
When you program a plugin, can I have this?

Thx kaesglocke

**Comment by blackrozes** [comment]
@kaesglocke 

no I dont program a plugin. With the custom firmware it works for me out of the box. 

Perhaps you only need to restart BLE adapter  

otherwise try this: 

- stopp iobroker ble adapter
- connect the web tool and do activation
- flash the firmware
- reconnected webtool after reboot of the device
- set "Advertising format" (I cant remember (Mi Like or custom just play with this))
- disconnect device from (PC / phone) 
- start iobroker ble adapter

**Comment by kaesglocke** [comment]
> @kaesglocke
> 
> no I dont program a plugin. With the custom firmware it works for me out of the box.
> 
> Perhaps you only need to restart BLE adapter
> 
> otherwise try this:
> 
> * stopp iobroker ble adapter
> * connect the web tool and do activation
> * flash the firmware
> * reconnected webtool after reboot of the device
> * set "Advertising format" (I cant remember (Mi Like or custom just play with this))
> * disconnect device from (PC / phone)
> * start iobroker ble adapter

Hello blackrozes,
thanks for your Howto.
You must set Advertising Mode to Mi like and enable Xiaomi Plugin in BLE Adater then it works.

Best greetings kaesglocke

**Comment by andreaskoerber** [comment]
Hello,
I have several of these Tempetarure/Humidity Sensors Working. For one of them, no data is received after October 1st, now, that is: RSSI and advertising data are recieved, but no values for humidity and temperature.
I deleted it from the object tree, and when the BLE ADapter in iobroker is set to allow new devices, it resinstalls, but only with th RSSI, the ManaufacturerData and the Advertising It advertises on 181a, though.
Re-Flashing in OTA to the original and re-flashing to alternative firmware does not help.
Any idea, how i can tell the BLE adapter to recognize the other data also and transfer them into objects, or how to make the device sending this data in the first place?

Thx in advance

**Comment by blackrozes** [comment]
> Hello, I have several of these Tempetarure/Humidity Sensors Working. For one of them, no data is received after October 1st, now, that is: RSSI and advertising data are recieved, but no values for humidity and temperature. I deleted it from the object tree, and when the BLE ADapter in iobroker is set to allow new devices, it resinstalls, but only with th RSSI, the ManaufacturerData and the Advertising It advertises on 181a, though. Re-Flashing in OTA to the original and re-flashing to alternative firmware does not help. Any idea, how i can tell the BLE adapter to recognize the other data also and transfer them into objects, or how to make the device sending this data in the first place?
> 
> Thx in advance


I had the same problem some time ago. Did you disconnect the device from (PC / phone) before start iobroker ble adapter again after flashing?

**Comment by andreaskoerber** [comment]
Yes, I flashed them OTA and then "disconnected" it. 
I just did it again. It re-connects, but still w/o the requested values.

**Comment by andreaskoerber** [comment]
Problem solved:
Somehow the advertising type was not set to "Mija" type. Doing so seems to have solved it.
