### ISSUE TITLE
fe95 service not working anymore since version 0.10.0

### ISSUE THREAD

**Issue by mswiege** [AlCalzone/ioBroker.ble#367]
I have a Xiaomi MiKettle that transmits its water temperature through the fe95 service.
In version 0.9.2 everything still worked as expected. The adapter created an object `<mac id>\services\fe95` and the value of fe95 got updated every 30 seconds.
Starting with version 0.10.0 these objects are not created anymore. I also tried the current Master branch but that one shows the same behaviour as 0.10.0. What also changed is that the signal value (rssi) is updated in milliseconds now and with that probably slows down the whole system (this problem can be solved by changing the Update Intervall in the settings though).

**Comment by AlCalzone** [comment]
Could you send me the adapter log (loglevel debug) please? Make sure it contains the MAC address of the device.

**Comment by mswiege** [comment]
Can I send it to you directly somehow? I would prefer not to make my log with my MAC addresses public.

**Comment by AlCalzone** [comment]
Nobody can do anything with your BLE MAC, but if you prefer you can send it to me via PM in the ioBroker forum.

**Comment by mswiege** [comment]
This is the log file of version 0.9.2 where it still works:
[Ble_0.9.2.log](https://github.com/AlCalzone/ioBroker.ble/files/4366089/Ble_0.9.2.log)
And this is the log from version 0.11.0 where it doesn't work anymore
[Ble_0.11.0.log](https://github.com/AlCalzone/ioBroker.ble/files/4366087/Ble_0.11.0.log)

The MiKettle has the mac 08:7c:be:86:23:9e and the value the adapter receives is for example "71208300769e2386be7c0809051002001c" where I don't know what all the numbers at the beginning are, but the last two chars are the celsius temperatur in hex (1c = 28°C).

**Comment by AlCalzone** [comment]
Actually, 0.11 is working and 0.9.2 is not. The xiaomi plugin creates its own states where it decodes the values from fe95. You should have a state `unknown (0x1005)`, which means the plugin doesn't know how to decode that value.

The weird thing is, the data is usually encoded as `1 length byte (n)` plus `n bytes data (little endian)`, in your case that would be `0x1c00`.
The data is then usually divided by 10 or 100, but here it seems like we need to divide by 256.
Could you send me a log where you turn on the kettle and heat up some water?

**Comment by AlCalzone** [comment]
Nevermind, I found a description of the new values. Apparently the byte before that is a status byte.
	// 0 - Idle
	// 1 - Heating
	// 2 - Cooling
	// 3 - Keeping warm

**Comment by AlCalzone** [comment]
I'll release an official version `v0.11.0` soon, which should create two states `temperature` and `kettleStatus` instead of the unknown one.

**Comment by mswiege** [comment]
Awesome. Thanks @AlCalzone

**Comment by AlCalzone** [comment]
0.11.0 will be out in a couple of minutes
