### ISSUE TITLE
RuuviTag FW update - skipping state ble.0.MAC.movementCounter because the object does not exist

### ISSUE THREAD

**Issue by alexhk** [AlCalzone/ioBroker.ble#381]
I have around 20 RuuviTags and updated one device to the latest firmware (2.5.9) for testing.

It seems there is a new movement counter in RAWv2 mode (which starts by default starting from this firmware version).

With ble.0 version 0.10.1 on this device I get the following warning in the log:

ble.0 | 2020-04-10 10:45:30.693 | warn | (7831) skipping state ble.0.MAC.movementCounter because the object does not exist
-- | -- | -- | --
ble.0 | 2020-04-10 10:45:29.414 | warn | (7831) skipping state ble.0.MAC.movementCounter because the object does not exist

From the firmware page:
https://lab.ruuvi.com/ruuvitag-fw/

> The RAWv2data contains all the data of RAWv1, as well as a movement counter to detect if tag has been handled, measurement sequence counter to detect reboots and missed packets as well as MAC address of the device for iOS users.

NB: I set my RSSI Update interval to 60000 (60 seconds?) but I get the warnings way more often than that.

**Comment by AlCalzone** [comment]
I had a typo in the plugin code. Should be working with v0.11.1.

The RSSI update interval does not change how often other states are updated. I added that option because some devices update RSSI every few milliseconds but their values don't change for much longer.
