### ISSUE TITLE
Adapter is not starting after updating to js-controller 3

### ISSUE THREAD

**Issue by dercaptainbc** [AlCalzone/ioBroker.ble#388]
After updating to js-controller 3 I got the following error, and adapter is not starting.
Current Version of ble : 0.11.2
Current Version of js-controller :  3.0.14

`Quelle|Zeit|debug|Meldung
-- | -- | -- | --
ble.0 | 2020-04-22 05:56:44.228 | error | (28452) unhandled promise rejection: TypeError: Cannot read property 'on' of undefined
ble.0 | 2020-04-22 05:56:44.225 | error | (28452) TypeError: Cannot read property 'on' of undefined at /opt/iobroker/node_modules/iobroker.ble/build/main.js:97:19 at Generator.next (<anonymous>) at fulfilled (/opt/iobroker/node_mo
ble.0 | 2020-04-22 05:56:44.222 | error | (28452) uncaught exception: Cannot read property 'on' of undefined

`

**Comment by AlCalzone** [comment]
This particular error will be fixed in the next version. However it happens for you because the adapter fails to load the Bluetooth driver. So either there's something wrong with your bluetooth setup or the adapter is not installed properly.
