### ISSUE TITLE
Instance stays "yellow" (no connection)

### ISSUE THREAD

**Issue by mswiege** [AlCalzone/ioBroker.ble#392]
Most recent versions of js-controller (3.0.18) and node (12.16.2) and current BLE (0.11.4).
BLE has shown node errors and I therefore had to rebuild it with `iobroker rebuild ble --install`. Afterwards it starts without error but in the admin console of the instances the BLE instance stays yellow (connected to host: true, Lebenszeichen: true, connected to BLE: false).

The log doesn't really show any issue:
```
ble.0 | 2020-04-25 13:10:32.834 | info | (22008) monitored services: fe95
-- | -- | -- | --
ble.0 | 2020-04-25 13:10:32.833 | info | (22008) enabled plugins: Xiaomi, _default
ble.0 | 2020-04-25 13:10:32.832 | info | (22008) loaded plugins: Xiaomi, mi-flora, ruuvi-tag, _default
ble.0 | 2020-04-25 13:10:32.620 | info | (22008) starting. Version 0.11.4 in /opt/iobroker/node_modules/iobroker.ble, node: v12.16.2, js-controller: 3.0.18
ble.0 | 2020-04-25 13:10:31.206 | debug | (22008) statesDB connected
ble.0 | 2020-04-25 13:10:31.205 | debug | (22008) States connected to redis: 127.0.0.1:9000
ble.0 | 2020-04-25 13:10:31.041 | debug | (22008) States create System PubSub Client
ble.0 | 2020-04-25 13:10:31.038 | debug | (22008) States create User PubSub Client
ble.0 | 2020-04-25 13:10:30.963 | debug | (22008) Redis States: Use Redis connection: 127.0.0.1:9000
ble.0 | 2020-04-25 13:10:30.961 | debug | (22008) objectDB connected
ble.0 | 2020-04-25 13:10:30.955 | debug | (22008) Objects connected to redis: 127.0.0.1:9001
ble.0 | 2020-04-25 13:10:30.940 | debug | (22008) Objects client initialize lua scripts
ble.0 | 2020-04-25 13:10:30.939 | debug | (22008) Objects create User PubSub Client
ble.0 | 2020-04-25 13:10:30.938 | debug | (22008) Objects create System PubSub Client
ble.0 | 2020-04-25 13:10:30.934 | debug | (22008) Objects client ready ... initialize now
ble.0 | 2020-04-25 13:10:30.899 | debug | (22008) Redis Objects: Use Redis connection: 127.0.0.1:9001
```

**Comment by AlCalzone** [comment]
Did you update Node.js by any chance? If yes, did you run the fixer afterwards?

**Comment by mswiege** [comment]
I did (from 10 to 12) after updating to js-controller 3.x
As suggested in the forum (https://forum.iobroker.net/topic/32481/js-controller-3-0-jetzt-im-latest/) I intentionally did not execute the fixer but let js-controller rebuild the instances. Since the only adapter (I have) that didn't work in this process I manually rebuild as mentioned above (and also mentioned in the forum).

I've now executed the fixer and this actually resolved the issue. The instance is now "green". Thanks for the hint.
Don't know if there is still something that can be improved in this regard in this adapter (since for all other adapters I have worked without the fixer). If not, feel free to close this issue. 
Thanks

**Comment by AlCalzone** [comment]
Bluetooth and some system ports need special permissions on the node executable which are lost after a node update. The fixer restores them.
That has nothing to do with the rebuild and is harder to detect since there is no error message.
So as long as you run the fixer after every node update, you should be fine.
