### ISSUE TITLE
negative degrees doesnt not work

### ISSUE THREAD

**Issue by zuvielx9** [AlCalzone/ioBroker.ble#40]
I have a xiaomi thermometer which currently hangs outside in the freezing temperatures. A temperature of 6553.1 °C is displayed.

**Comment by AlCalzone** [comment]
Which version do you use?

**Comment by AlCalzone** [comment]
Negative temperature support was added in https://github.com/AlCalzone/ioBroker.ble/commit/e7b127a0e1d962dc559a71c1cb4b3bb63b94ad0a (and verified as fixed)

**Comment by zuvielx9** [comment]
sorry, it was still on version 0.5.2. it works now, thank you!
