### ISSUE TITLE
Version 0.11.6 does not start and keeps on "rebuilding"

### ISSUE THREAD

**Issue by Marty56** [AlCalzone/ioBroker.ble#401]
`

host.ioBroker-RasPi4 | 2020-05-10 04:34:39.155 | info | Restart adapter system.adapter.ble.0 because enabled
-- | -- | -- | --
host.ioBroker-RasPi4 | 2020-05-10 04:34:39.153 | error | instance system.adapter.ble.0 terminated with code 13 (13)
ble.0 | 2020-05-10 04:34:38.552 | error | (2189) Terminating because A dependency requires a rebuild.

`

**Comment by Marty56** [comment]
Ich habe den Adapter deinstallieren müssen und wieder installiert. Dann hat es funktioniert.

**Comment by AlCalzone** [comment]
Welche JS-Controller-Version? Mit dem 3.1-Stable-Release sollte das Geschichte sein.

**Comment by Marty56** [comment]
3.1.3

**Comment by Apollon77** [comment]
Hast nch noch das volle log vom js-controller?

**Comment by Marty56** [comment]
Sorry, habe ich nicht mehr.

Aus der Erinnerung hat er sich beschwert, dass hcicontroller (?) mit einer falschen Node Version compiliert ist und dass man einen npm rebuild machen soll.
Allerdings wurde ein Verzeichnis angegeben, das nach den ".../nodes_modules" mit einem '@' Zeichen anfing und das ich nicht gefunden habe.

**Comment by AlCalzone** [comment]
> Vielleicht lag es darin, dass ich auf Node 12 umgestellt habe.

Und genau deswegen wird der Rebuild benötigt. Allerdings sieht mir

> instance system.adapter.ble.0 terminated with code 13 (13)

danach aus dass JS-Controller das nicht merkt. @Apollon77 kann es sein, dass `procs[id]` in https://github.com/ioBroker/ioBroker.js-controller/blob/d3ee7e6ab59dd53a85179f1c82908e9c692a81e4/main.js#L3268 aus irgendeinem Grund nicht mehr definiert ist?

**Comment by AlCalzone** [comment]
O

**Comment by Apollon77** [comment]
Ohne log kann man nur raten. Das log sollte ja sofort da sein wenn man es nochmal startet. 

Die Variable wäre nur undefiniert wenn man den Adapter/Instanz löschen würde

**Comment by AlCalzone** [comment]
@Marty56 bitte wieder aufmachen, wenn das Problem weiterhin besteht.
