### ISSUE TITLE
(1967) uncaught exception: Cannot set property 'mtu' of undefined

### ISSUE THREAD

**Issue by r0b1zZle** [AlCalzone/ioBroker.ble#406]
**Description**  
BLE Adapter is connecting well and consequently getting data from my flower sensors. Unfortunately every like 20 seconds the adapter is restarting due to an error.

**Expected behavior**  
No errors.

**Screenshots & Logfiles**  
`
host.raspberrypi4-iob | 2020-05-28 00:26:12.683 | info | Restart adapter system.adapter.ble.0 because enabled
-- | -- | -- | --
host.raspberrypi4-iob | 2020-05-28 00:26:12.683 | info | instance system.adapter.ble.0 terminated with code 0 (NO_ERROR)
host.raspberrypi4-iob | 2020-05-28 00:26:12.683 | error | Caught by controller[6]: noble: unknown peripheral 001a220754a6 handle notify!
host.raspberrypi4-iob | 2020-05-28 00:26:12.683 | error | Caught by controller[5]: at Hci.emit (events.js:315:20)
host.raspberrypi4-iob | 2020-05-28 00:26:12.683 | error | Caught by controller[5]: at NobleBindings.onAclDataPkt (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:288:15)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at AclStream.push (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:33:10)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at AclStream.emit (events.js:327:22)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at Gatt.onAclStreamData (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:133:26)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at Object.callback (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:329:10)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at Gatt.emit (events.js:315:20)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at NobleBindings.onMtu (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:277:8)
host.raspberrypi4-iob | 2020-05-28 00:26:12.682 | error | Caught by controller[5]: at NobleBindings.emit (events.js:315:20)
host.raspberrypi4-iob | 2020-05-28 00:26:12.681 | error | Caught by controller[5]: at Noble.onMtu (/opt/iobroker/node_modules/@abandonware/noble/lib/noble.js:564:18)
host.raspberrypi4-iob | 2020-05-28 00:26:12.681 | error | Caught by controller[5]: TypeError: Cannot set property 'mtu' of undefined
host.raspberrypi4-iob | 2020-05-28 00:26:12.681 | error | Caught by controller[4]: at Hci.emit (events.js:315:20)
host.raspberrypi4-iob | 2020-05-28 00:26:12.681 | error | Caught by controller[4]: at NobleBindings.onAclDataPkt (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:288:15)
host.raspberrypi4-iob | 2020-05-28 00:26:12.681 | error | Caught by controller[4]: at AclStream.push (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/acl-stream.js:33:10)
host.raspberrypi4-iob | 2020-05-28 00:26:12.681 | error | Caught by controller[4]: at AclStream.emit (events.js:327:22)
host.raspberrypi4-iob | 2020-05-28 00:26:12.680 | error | Caught by controller[4]: at Gatt.onAclStreamData (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:133:26)
host.raspberrypi4-iob | 2020-05-28 00:26:12.680 | error | Caught by controller[4]: at Object.callback (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/gatt.js:329:10)
host.raspberrypi4-iob | 2020-05-28 00:26:12.680 | error | Caught by controller[4]: at Gatt.emit (events.js:315:20)
host.raspberrypi4-iob | 2020-05-28 00:26:12.680 | error | Caught by controller[4]: at NobleBindings.onMtu (/opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:277:8)
host.raspberrypi4-iob | 2020-05-28 00:26:12.680 | error | Caught by controller[4]: at NobleBindings.emit (events.js:315:20)
host.raspberrypi4-iob | 2020-05-28 00:26:12.680 | error | Caught by controller[4]: at Noble.onMtu (/opt/iobroker/node_modules/@abandonware/noble/lib/noble.js:564:18)
host.raspberrypi4-iob | 2020-05-28 00:26:12.679 | error | Caught by controller[4]: TypeError: Cannot set property 'mtu' of undefined
host.raspberrypi4-iob | 2020-05-28 00:26:12.679 | error | Caught by controller[3]: noble: unknown peripheral 001a220754a6 connected!
host.raspberrypi4-iob | 2020-05-28 00:26:12.679 | error | Caught by controller[2]: noble: unknown peripheral 001a220754a6 disconnected!
host.raspberrypi4-iob | 2020-05-28 00:26:12.678 | error | Caught by controller[1]: noble: unknown peripheral 001a220754a6 connected!
ble.0 | 2020-05-28 00:26:12.162 | info | (1967) Terminated (NO_ERROR): Without reason
ble.0 | 2020-05-28 00:26:12.161 | info | (1967) terminating
ble.0 | 2020-05-28 00:26:12.150 | error | (1967) TypeError: Cannot set property 'mtu' of undefined at Noble.onMtu (/opt/iobroker/node_modules/@abandonware/noble/lib/noble.js:564:18) at NobleBindings.emit (events.js:315:20) at Nobl
ble.0 | 2020-05-28 00:26:12.149 | error | (1967) uncaught exception: Cannot set property 'mtu' of undefined
ble.0 | 2020-05-28 00:26:12.143 | info | (1967) stopping scan
ble.0 | 2020-05-28 00:26:12.141 | error | (1967) TypeError: Cannot set property 'mtu' of undefined at Noble.onMtu (/opt/iobroker/node_modules/@abandonware/noble/lib/noble.js:564:18) at NobleBindings.emit (events.js:315:20) at Nobl
ble.0 | 2020-05-28 00:26:12.140 | error | (1967) uncaught exception: Cannot set property 'mtu' of undefined
`

**Versions:**  
 - Adapter version: 0.11.6
 - JS-Controller version: 2.2.10
 - Node / Nodejs version: v12.17.0
 - Operating system: Raspbian (Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux)

**Comment by AlCalzone** [comment]
Looks like an error in https://github.com/abandonware/noble
Would you mind raising an issue there with the log you posted here?

**Comment by r0b1zZle** [comment]
> Looks like an error in https://github.com/abandonware/noble
> Would you mind raising an issue there with the log you posted here?

Sure. I opened an issue [here](https://github.com/abandonware/noble/issues/91).

**Comment by AlCalzone** [comment]
Should no longer be an issue in v0.12.0 since scanning is now done in a separate process. If this continues to be a problem, please reopen.
