### ISSUE TITLE
Adapter Scans every 30 seconds

### ISSUE THREAD

**Issue by manoloxxl** [AlCalzone/ioBroker.ble#421]
Hi,

as far as I can see in my log the ble adapter is scanning every 30 seconds:

`

le.0 | 2020-08-10 18:01:28.610 | info | (22731) starting scan for services ["fe95"]
-- | -- | -- | --
ble.0 | 2020-08-10 18:01:28.464 | info | (22731) stopping scan
ble.0 | 2020-08-10 18:00:58.610 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 18:00:58.449 | info | (22731) stopping scan
ble.0 | 2020-08-10 18:00:28.611 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 18:00:28.426 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:59:58.614 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:59:58.407 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:59:28.608 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:59:28.384 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:58:58.612 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:58:58.365 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:58:28.611 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:58:28.349 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:57:58.611 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:57:58.334 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:57:28.606 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:57:28.319 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:56:58.609 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:56:58.308 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:56:28.604 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:56:28.290 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:55:58.609 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:55:58.269 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:55:28.617 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:54:58.216 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:54:28.601 | info | (22731) starting scan for services ["fe95"]
ble.0 | 2020-08-10 17:54:28.198 | info | (22731) stopping scan
ble.0 | 2020-08-10 17:53:58.604 | info | (22731) starting scan for services ["fe95

`

How can I change this to maybe 2 or 5 minutes? The RSSI Scan is set to 50minutes

Best Regards
Manuel

**Comment by AlCalzone** [comment]
The scan should always be active and not start and stop all the time, rssi has nothing to do with that... my guess is that something is interfering with the Bluetooth interface, maybe another application or adapter.

**Comment by manoloxxl** [comment]
Hi. There is also Radar2 running on same machine. Is there a way to make both tools running same time?

**Comment by AlCalzone** [comment]
Only if you have two Bluetooth interfaces, e.g. One internal plus one stick

**Comment by manoloxxl** [comment]
Okay. Thanks. So i will buy an additional stick.
