### ISSUE TITLE
Ruuvi-Tag Pressure Resolution

### ISSUE THREAD

**Issue by Knicko83** [AlCalzone/ioBroker.ble#424]
Hi, I'm using the BLE adapter version 0.11.6 in IoBroker in combination with Ruuvi Tags RAWv2 (https://lab.ruuvi.com/dfu/)

The "pressure" measurement value is shown as INT value only, without any decimals, whereas e.g. on my smartphone I can see that the value is transmitted with a higher resolution (2 decimals on android app).

Is there a possibility to increase the used accuracy?
![ruuvitagiobroker](https://user-images.githubusercontent.com/30951261/91094286-e1534f80-e65a-11ea-95d4-71cbbb0965c1.jpg)

**Comment by AlCalzone** [comment]
Yes, the value is rounded. I can change that.

**Comment by AlCalzone** [comment]
Fixed in `v0.11.8`

**Comment by Knicko83** [comment]
Installed and works like a charm!
Mille gracie, and many kudos!

![RuuviPressureAccuracy](https://user-images.githubusercontent.com/30951261/91299158-7b251480-e7a1-11ea-89f3-3d384adcb76b.jpg)
