### ISSUE TITLE
Terminating because No compatible BLE 4.0 hardware found! intel bluetooth

### ISSUE THREAD

**Issue by partyzonetut** [AlCalzone/ioBroker.ble#472]
help plz. cant connect with this error
Terminating because No compatible BLE 4.0 hardware found!
Windows 10, intel wireless bluetooth 5.0 USB\VID_8087&PID_0AAA. maybe intel Wireless AC-9560
noble, hci - installed
Is this driver only for bluetooth 4.0?
Thank you

**Comment by AlCalzone** [comment]
To be honest, I don't know. This adapter just uses the `noble` library to use Bluetooth.

If your hardware is not supported by that, there's nothing I can do.
You might want to open an issue in https://github.com/abandonware/noble/issues instead.
