### ISSUE TITLE
Flower Care

### ISSUE THREAD

**Issue by Stiesel** [AlCalzone/ioBroker.ble#489]
**Describe the bug**  
Hello I recently ordered new Flower Care sensors. unfortunately we are not found. firmeware 3.2.4
the old sensors work without problems

Hardware:
HHCCJCY01HHCC
Q/CYHHC0003-2017
4.1 BLE
CMIIT ID: 2016DP0940
FCC ID: 2AJEPHHCCJCY01HHCC

**To Reproduce**  
No found

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.12.0
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: raspi os

**Additional context**  
Hello I recently ordered new Flower Care sensors. unfortunately we are not found. firmeware 3.2.4
the old sensors work without problems

**Comment by AlCalzone** [comment]
If they are not found at all, I'm not sure there's anything to be done here.
If they just don't send any data, you might have to initialize them with the App.

**Comment by Stiesel** [comment]
It works with the Flower Care app. I can also see the devices via Bluetooth on the smartphone and also look at their MAC address.

**Comment by AlCalzone** [comment]
Oh please check the state (not in the config) for allow new devices. Maybe that is set to false

**Comment by Stiesel** [comment]
you mean in iobroker  Objects ble.0 Options allow new adevice = True

**Comment by AlCalzone** [comment]
do you find them if you scan on the console with `hcitool lescan`?

**Comment by Stiesel** [comment]
![Screenshot_20201210-182551_RaspController](https://user-images.githubusercontent.com/75696888/101807367-5321ad00-3b15-11eb-9b23-fa1eefa6a951.jpg)
![Screenshot_20201210-182651_Chrome](https://user-images.githubusercontent.com/75696888/101807382-56b53400-3b15-11eb-829d-11807402a357.jpg)
yes there is also a lot found, but not under BLE

**Comment by Stiesel** [comment]
Done, uninstalled and reinstalled BLE, now he finds everything Thank you
