### ISSUE TITLE
Set AllowNewDevices to false after installation

### ISSUE THREAD

**Issue by Buddinski88** [AlCalzone/ioBroker.ble#534]
**Describe the bug**  
In the settings you can check the box "Allow capturing devices without sent data". This option is not enabled after installation, but new devices are added anyway.

**To Reproduce**  
1. Install BLE-Apdater
2. Go to Instances and open BLE settings
3. Check it the checkbox is active, should not be active
4. Go to objects and there to 0.ble and check if allowNewDevices is false or true

**Expected behavior**  
After the default installation of the adapter, allowNewDevices should be set to false because the checkbox is not active in the adapter settings.

**Screenshots & Logfiles**  
none

**Versions:**  
 - Adapter version: 0.12.0
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: ubuntu 20.04.1 LTS

**Additional context**  
none

**Comment by AlCalzone** [comment]
Do you mean allowNewDevices (found in the object list) or the config option to capture devices without service data?

**Comment by Buddinski88** [comment]
I mean allowNewDevices from the object list. I thought that controlled the check mark in the settings.

**Comment by AlCalzone** [comment]
Okay that is not the same
