### ISSUE TITLE
Xiaomi Motion Sensor 2 (RTCGQ02LM)

### ISSUE THREAD

**Issue by Anzic23** [AlCalzone/ioBroker.ble#675]
Can you add support for this motion sensor? When you press the pairing button, the sensor appears in the objects, but has only the 'fe95' and rssi services

**Comment by AlCalzone** [comment]
Maybe if you show some of the data it sends

**Comment by Anzic23** [comment]
ble.0.54:ef:44:e3:52:c6.services.fe95 - 30588d0a01c652e344ef5408

**Comment by AlCalzone** [comment]
The entries starting with 30 don't contain any useful data sadly
