### ISSUE TITLE
Compatibility check to js-controller 4.0

### ISSUE THREAD

**Issue by ioBrokerChecker** [AlCalzone/ioBroker.ble#707]
Dear Adapter developer,

with js-controller 4.0 object definitions are now also checked that min/max in only provided for number/mixed objects and that the type of the default value matches to the object type.

If something is not correct this is logged as 'warning' or 'info' log.

Please also make sure to update to the lastest @iobroker/testing dependency 2.5.4 or to accept the PR from Apollon77 for legacy testing!

Please spent some time to verify your adapter by ideally starting with a fresh instance and do some actions and verify the log. If you see a warn or info log there from these checks please adjust the adapter and fix the relevant cases.

For questions please refer to ioBroker/ioBroker.js-controller#1749

Please close the issue after you checked it.

Thank you very much for your support to get the best experience for the growing numbers of ioBroker users!

**Comment by asutpshnik** [comment]
Now the version is not compatible with js-controller 4.0.9
After starting BLE driver, cyclic attempts to rebuild npm components/libs
By updating js-controller, I received a non-working driver, the ble sensors are not polled (((

**Comment by AlCalzone** [comment]
This is a bug in js-controller that has already been fixed: https://github.com/ioBroker/ioBroker.js-controller/pull/1805

If you're participating in a beta-test, this can always happen.

**Comment by Apollon77** [comment]
@asutpshnik Ok, now one step after the other.

1.) an npm rebuild issue only happens when you upgrade nodejs ... this has nothing to do with the js-controller
2.) Yes, one library used inside ble adapter do not allow a proper rebuild of itself. This is nothing te adapter can do anything. We alreay work with the library owner to get an update to enhance this.
3.) After 3 rebuild tries the log contain exact details on how to fix it yourself, please read the logs. In fact yu need to run "npm install -- production" inside /opt/iobroker/node_modules/iobroker.ble - this should fix this issue temporariely

**Comment by Apollon77** [comment]
For completeness: This is the "fix" we need in that one library https://github.com/abandonware/node-bluetooth-hci-socket/pull/39 ... The PR is already merged, just the release is pending ... and before someone complains that also canvas is affected ... yes it has the same issue https://github.com/Automattic/node-canvas/pull/1982 (PR still open, likes there welcome)

**Comment by asutpshnik** [comment]
> 3.) After 3 rebuild tries the log contain exact details on how to fix it yourself, please read the logs. In fact yu need to run "npm install -- production" inside /opt/iobroker/node_modules/iobroker.ble - this should fix this issue temporariely
3.) - helped me, the driver starts up and works, thanks!

**Comment by Apollon77** [comment]
@asutpshnik Thank you for your info. We hope to get the library update soon then it should be better in the future

**Comment by TDCroPower** [comment]
here too, with the command in the correct directory the adapter works again.
