### ISSUE TITLE
"ENODEV, No such device" after PI Update

### ISSUE THREAD

**Issue by Tombra1889** [AlCalzone/ioBroker.ble#725]
**Describe the bug**  
ENODEV, No such device after PI Update

**Screenshots & Logfiles**  
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/60692414/161225782-2ed7f30a-14e0-4478-9642-6acf4873aa0d.png">

**Versions:**  
 - Adapter version: 0.12.0
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: raspberry PI

**Comment by AlCalzone** [comment]
If you don't mind, please ask for help on the ioBroker forums. I'm not very familiar with the hardware/os-level configuration and this seems to be a problem outside the BLE adapter.
