### ISSUE TITLE
Cannot find module '@abandonware/bluetooth-hci-socket

### ISSUE THREAD

**Issue by Skol6** [AlCalzone/ioBroker.ble#762]
Hi,

also ich hab @abandonware/bluetooth-hci-socket und @abandonware/noble installiert.

Im Iobroker Log finde ich immer folgende Fehlermeldung:
`Cannot find module '@abandonware/bluetooth-hci-socket'Require stack:- /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/hci.js- /opt/iobroker/node_modules/@abandonware/noble/lib/hci-socket/bindings.js- /opt/iobroker/node_modules/@abandonware/noble/lib/resolve-bindings.js- /opt/iobroker/node_modules/@abandonware/noble/index.js- /opt/iobroker/node_modules/iobroker.ble/build/scanProcess.js`

Hast du irgendeine Idee woran das liegen könnte?
Die Dateien liegen aber genau in dem Ordner...
Läuft auf einem Raspberry Pi 3.

Node.js: v19.1.0
NPM: v9.1.2

Vielen Dank!

**Comment by derherrgraf** [comment]
me too...sowohl bei Version 0.13.0 und 0.13.3
Node: v19.0.0
NPM: 9.6.0

**Comment by AlCalzone** [comment]
Was ist der Inhalt von `/opt/iobroker/package.json`?
