### ISSUE TITLE
Adapter ist grün und Findet Geräte aber Aktualisiert Daten nicht

### ISSUE THREAD

**Issue by haahne** [AlCalzone/ioBroker.ble#771]
Moin, Adapter ist grün.
DriverState: PoweredOn
Connection: true
 Adapter findet auch die Geräte und aktualisiert einmalig die States aber danach nicht mehr.
Erst wenn Adapter neu Gestartet wird.

**Comment by Predator83** [comment]
Gleiches Problem bei mir. Tritt erst seit Upgrade auf nodejs 14 auf. Ich benutze aktuell die 0.13.1 Version. 0.13.0 war ständig auf rot mit der neuen nodejs (14) Version.

**Comment by Predator83** [comment]
Downgrade auf 0.13.0 mit 

iobroker upgrade ble@0.13.0

In Kombination mit

iobroker fix
iobroker rebuild ble 
iobroker fix

Macht den Adapter zumindest wieder funktionsfähig, auch in Kombi mit nodejs 14

**Comment by AlCalzone** [comment]
Bitte mit 0.13.2 erneut testen.

**Comment by Predator83** [comment]
Scheint auf den ersten Blick zu funktionieren. Ich meld mich falls mir noch was auffällt 

danke für das schnelle Update

**Comment by allahopp** [comment]
Bei mir wurden die Daten ebenfalls nicht mehr aktualisiert, mit der 0.13.2 funktioniert es wieder. Vielen Dank!
