### ISSUE TITLE
Hohe CPU-Last trotz UUID

### ISSUE THREAD

**Issue by ammawel** [AlCalzone/ioBroker.ble#772]
Hohe CPU-Last trotz UUID

Die Verwendung des BLE-Adapters erhöht die CPU-Aktivität kontinuierlich von normal 3% bis 4% auf Werte über 40%. Die Deaktivierung von BLE senkt sofort wieder auf den geringen Wert.
Eine Änderung der überwachten Dienste von * auf 0xFE95 verlangsamt den Prozess etwas, hält ihn aber nicht auf. Da auch die CPU-Temperatur entsprechend von rund 40°C auf mehr als 75°C wächst, habe ich BLE angehalten.
Vielen Dank für jede Hilfe!

System:
Raspi 4, 8GB, Bullseye 64 Bit, node.js v16.18.1
BLE Version 0.13.1
Für BLE: 3 Xiaomi-Thermometer / Hygrometer
Adaptereinstellung:
![2022-12-30_214157](https://user-images.githubusercontent.com/51128844/210110572-9ce5ae58-e1cb-43a6-9fae-b55e01e89814.png)

**Comment by AlCalzone** [comment]
Irgend etwas auffälliges im iobroker log?
Wie viele Geräte?
Trat das vor der 0.13.1 schon auf? Falls nein, hilft ein downgrade?

**Comment by ammawel** [comment]
Erstmal Danke für die schnelle Antwort.
Nein, keine weiteren Auffälligkeiten, LOG gibt auch nichts her.
Wie geschrieben 3 Geräte.
Kann ich nichts zu sagen: Hatte bisher IOB auf einem Pi 3, da traten keine Probleme (mit identischer Konfiguration) auf. Habe den Pi 4 komplett neu aufgesetzt, alle Updates sind eingespielt.
Im Forum gibt es auch einige Threads zu BLE auf PI 4 - leider alle ohne Lösung...

**Comment by ammawel** [comment]
Ich habe jetzt mal ein Downgrade auf 0.13.0 durchgeführt (zeitlich könnte meine Umstellung auf PI 4 mit dem Update von 0.13.0 auf 0.13.1 übereinstimmen):

- die CPU-Last bleibt niedrig, aber
- es werden keine aktualisierten Werte angezeigt


das LOG weist einen Fehler auf: "noble.on is not a function"

```
2022-12-31 00:08:10.837  - debug: ble.0 (8551) Redis Objects: Use Redis connection: 127.0.0.1:9001
2022-12-31 00:08:10.891  - debug: ble.0 (8551) Objects client ready ... initialize now
2022-12-31 00:08:10.894  - debug: ble.0 (8551) Objects create System PubSub Client
2022-12-31 00:08:10.896  - debug: ble.0 (8551) Objects create User PubSub Client
2022-12-31 00:08:10.997  - debug: ble.0 (8551) Objects client initialize lua scripts
2022-12-31 00:08:11.006  - debug: ble.0 (8551) Objects connected to redis: 127.0.0.1:9001
2022-12-31 00:08:11.048  - debug: ble.0 (8551) Redis States: Use Redis connection: 127.0.0.1:9000
2022-12-31 00:08:11.074  - debug: ble.0 (8551) States create System PubSub Client
2022-12-31 00:08:11.077  - debug: ble.0 (8551) States create User PubSub Client
2022-12-31 00:08:11.162  - debug: ble.0 (8551) States connected to redis: 127.0.0.1:9000
2022-12-31 00:08:11.566  - info: ble.0 (8551) starting. Version 0.13.0 in /opt/iobroker/node_modules/iobroker.ble, node: v16.19.0, js-controller: 4.0.24
2022-12-31 00:08:11.624  - info: ble.0 (8551) loaded plugins: Xiaomi, mi-flora, ruuvi-tag, _default
2022-12-31 00:08:11.626  - info: ble.0 (8551) enabled plugins: Xiaomi, _default
2022-12-31 00:08:11.627  - info: ble.0 (8551) monitoring all services
2022-12-31 00:08:11.648  - info: ble.0 (8551) starting scanner process...
2022-12-31 00:08:11.885  - error: ble.0 (8551) noble.on is not a function
```

**Comment by ammawel** [comment]
Bin wieder zurück bei 0.13.1, bei nur drei Geräten hatte ich alles deinstalliert, neu gestartet und BLE neu installiert.

- die 3 Geräte werden gefunden, allerdings nicht vollständig
- bei zwei Geräten fehlt der Batteriestatus
- bei allen Geräten wird lediglich rssi aktualisiert, keine anderen Werte. Das könnte vorher auch schon der Fall gewesen sein, bei nur drei Thermometern fällt das u.U. nicht auf.
Dieser Fehler könnte mit der Meldung von @haahne von heute in Verbindung stehen, nach der bei seinen Geräten die Daten ebenfalls nicht aktualisiert werden ([Adapter ist grün und Findet Geräte aber Aktualisiert Daten nicht #771](https://github.com/AlCalzone/ioBroker.ble/issues/771) )

![image](https://user-images.githubusercontent.com/51128844/210119236-82d1708c-b6af-489c-8c2f-9fbccda3fc2b.png)

**Comment by haahne** [comment]
Hab genau das selbe , und auch mit der erhöhten CPU Last. Bin sonst mit 4 Kernen unter Proxmox bei 8-9% Last . Jetzt mit BLE bei um die 20%. Habe auch alle Versionen bis 0.12.0 versucht aber keine Besserung da dann die Meldung kommt : noble ist Not .on function.

**Comment by Apollon77** [comment]
Was just cpu going crazy or also ram usage?

**Comment by muhagl** [comment]
Auch bei mir das gleiche:
Master:
- Betriebssystem Debian **11** Intel(R) Core(TM) i5-10600T CPU @ 2.40GHz 15.48 GB Node.js v16.19.0 NPM 8.19.3
- erhöhte CPU-Last von 4% auf kontinuiertlich steigernd bis ca. 10%
- bei der RAM-Nutzung keine signifikante Steigerung erkennbar
- nach Downgrade auf 0.13.0 CPU-Last wieder unauffällig - jedoch keine Aktualisierung der Temperatur/Feuchte
- im Log nach Downgrade: noble.on is not a function

Client:
- Raspberry Pi 3 Debian **10** 600 MHz ARMv7 Processor rev 4 (v7l) 923.21 MB Node.js v16.19.0 NPM 8.19.3
- keine erhöhte CPU-Last bei der Version 0.13.1 erkennbar (liegt immer bei 4% - 8%)
- Messwerte für Temperatur und Feuchte werden mit beiden Versionen 0.13.0 und 0.13.1 aktualisiert

Ich habe die Version nun wieder hochgezogen auf die Version 0.13.1 (nach Update aller übrigen Adapter auf aktuellen Stand):
- nach einer Stunde keine Erhöhung der CPU-Last erkennbar ... Prozessauslastung von io.ble.0 ist ebenfalls bisher unauffällig
- scheinbar dauert es länger bis Auswirkungen erkennbar sind - werde weiter beobachten und berichten

VG
Hans

**Comment by ammawel** [comment]
Guten Morgen,

auch bei mir ist keine Steigerung der RAM-Nutzung erkennbar.
Eine vollständige Deinstallation des Adapters und Neuinstallation mit v0.13.1 hat keine Änderung oder Verbesserung gebracht.

VG
Achim

**Comment by AlCalzone** [comment]
0.13.2 bringt wieder die alte Version von `noble` mit. Falls das das Problem nicht löst, bitte Bescheid geben.
