### ISSUE TITLE
_default pluging always handling

### ISSUE THREAD

**Issue by partyzonetut** [AlCalzone/ioBroker.ble#775]
The driver loads two plugins _default, Xiaomi. But always handles only by default (few days). How to assign specific device handling by Xiaomi plugin? 
Is it possible to do this manually in future versions?
<html>
<body>

2023-01-27 09:29:25.844 - debug: ble.0 (11472) updating rssi state for a4:c1:38:ec:83:b8
--
2023-01-27 09:29:25.845 - debug: ble.0 (11472) discovered peripheral a4:c1:38:ec:83:b8
2023-01-27 09:29:25.845 - debug: ble.0 (11472) has advertisement: true
2023-01-27 09:29:25.845 - debug: ble.0 (11472) has serviceData: true
2023-01-27 09:29:25.845 - debug: ble.0 (11472) serviceData = []
2023-01-27 09:29:25.846 - debug: ble.0 (11472) has manufacturerData: true
2023-01-27 09:29:25.846 - debug: ble.0 (11472) manufacturerData =
2023-01-27 09:29:25.846 - debug: ble.0 (11472) plugin _default is handling a4:c1:38:ec:83:b8
2023-01-27 09:29:25.846 - debug: ble.0 (11472) updating rssi state for a4:c1:38:ec:83:b8
2023-01-27 09:29:25.849 - debug: ble.0 (11472) a4:c1:38:ec:83:b8 > got values: {}
2023-01-27 09:29:25.850 - debug: ble.0 (11472) a4:c1:38:ec:83:b8 > got values: {}

</body>
</html>

**Comment by AlCalzone** [comment]
Which log level is this log from?
If not debug then please make another one with "debug" level.

It doesn't look like there is any data, so nothing the xiaomi plug-in can use to determine it should be handling the decoding.

**Comment by partyzonetut** [comment]
Hello. Its debugging level.
The sensor  LYWSD03MMC  was flashed and worked before reinstalling iobroker. Required plugin is not defined  now

**Comment by AlCalzone** [comment]
>  LYWSD03MMC

You have the alternative firmware for this and configured it to send the correct advertisements, correct?

**Comment by AlCalzone** [comment]
> serviceData = []

This should read
```
serviceData = ["fe95"]
```
for the xiaomi plugin to be able to handle it. Seems to me the device isn't configured correctly.

**Comment by Skol6** [comment]
Mhmm I do have the same issue.
All BLE Xiaomi thermomethers have worked fine. 
Yesterday I had to reinstall IObroker completely and also the BLE adapter.
Afterwards some are identified correctly, but most not.
I will try to reinstall the firmeware, but it is still strange

**Comment by Skol6** [comment]
Also noch ein Update:
- ich hab nochmal bei allen Thermometern die Option "Mi Like" gesetzt und jetzt läuft es einwandfrei
- Keine Ahnung warum und wieso, aber die Teile verlieren den Status beim Batteriewechsel. D.h. nach jedem Wechsel muss der Status erneut gesetzt werden.
- Hat wer eine Firmwareempfehlung?

Ich hab mal hier ein Bugticket aufgemacht: [https://github.com/atc1441/ATC_MiThermometer/issues/316](https://github.com/atc1441/ATC_MiThermometer/issues/316)

**Comment by Skol6** [comment]
Und hier eine neue Firmware gefunden.
Die hat das Problem nicht. Man muss aber mit 2 Flashern arbeiten
Anleitung ist hier zu finden [https://github.com/pvvx/ATC_MiThermometer/discussions/475#discussioncomment-8328541](https://github.com/pvvx/ATC_MiThermometer/discussions/475#discussioncomment-8328541)

**Comment by AlCalzone** [comment]
> Some are using "FE95" as wished, but are not using xiaomi adapter:

Das ist im Adapter bisschen blöd gelöst... Das Paket was da empfangen wurde, enthält keine Nutzdaten (nur MAC-Adresse), lässt sich aber als Xiaomi-Paket parsen. Der Adapter geht aufgrund der fehlenden Nutzdaten davon aus, dass es möglicherweise doch kein Xiaomi-Paket ist, und merkt sich das.

**Comment by Skol6** [comment]
Sorry. das Log hab ich nicht mehr.
Bei Debug "All" waren so dermaßen viele Nachrichen das es wirklich schwer war.

Aber mit der neuen Firmware ist alles OK. Und der zustand wird nach dem Batteriewechsel gespeichert.

**Comment by AlCalzone** [comment]
Dann empfehlen wir diesen Kommentar mal als Lösung:
https://github.com/AlCalzone/ioBroker.ble/issues/775#issuecomment-1920654835
