### ISSUE TITLE
Add bthome support (as plugin)

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/ioBroker.ble#792]
The new Shelly BLU devices (like shelly blu button 1) send information via BLE in a open format (bthome). It looks like this is the right place to implement a direct connection to ioBroker. What do you think?

Example implementation for Shelly Scripting: https://github.com/ALLTERCO/shelly-script-examples/blob/5aa9ac255b8577acb4be4f388c975594bf5fd5f9/ble-shelly-btn-gateway-for-other-devices.js#L78-L143

See https://bthome.io

**Comment by klein0r** [comment]
Let me know if you need a Shelly BLU Button 1

**Comment by AlCalzone** [comment]
Actually, why not? :)

**Comment by ammawel** [comment]
Hallo,
wie ist denn der Stand der Dinge bzg. BTHome? 
Konkret: Werden z.B. die Shelly Bluetooth-Geräte wie Blu-Button oder Blu-Motion in absehbarer Zeit unterstützt?
Danke und Gruß
Achim

**Comment by AlCalzone** [comment]
Haste eines für mich? :)

**Comment by klein0r** [comment]
@AlCalzone Kann Dir einen BLU Motion und BLU Button schicken. Schick mir mal Deine Adresse per Mail

**Comment by H-K-47** [comment]
Wir ist hier der Stand? Wurde da was versendet bzw. geht es vor ran?

**Comment by klein0r** [comment]
Hab keine Mail bekommen und daher auch nix verschickt...

**Comment by AlCalzone** [comment]
Ich hab die Nachricht nicht gesehen 😇
Adresse kommt gleich!

**Comment by H-K-47** [comment]
alles angekommen? wirds hier weiter gehen? danke

**Comment by klein0r** [comment]
@H-K-47 Ich weiß nicht ob es mit regelmäßigen Fragen schneller geht 😄

**Comment by AlCalzone** [comment]
Bin jetzt erst mal ne Woche im Urlaub. Ständig Fragen hilft nicht 🤷🏻‍♂️

**Comment by H-K-47** [comment]
Nun mal ganz locker ihr beiden "ständig fragen" lächerlich - ich habe das 2te mal gefragt - ohne meine erste Frage wäre es im Sand verlaufen und nach 2 Wochen zu fragen ob es denn jetzt geklappt hat ist doch normal?

**Comment by klein0r** [comment]
@H-K-47 Was war denn nicht locker? Weder @AlCalzone noch ich haben etwas davon, wenn das Feature implementiert wird. Wenden aber trotzdem Zeit und Geld dafür auf.

- Wird das hier wahrscheinlich noch dauern? Ja.
- Wird es regelmäßige Status-Updates geben? Nein.

**Comment by AlCalzone** [comment]
Um es kurz zu halten - wenn ich Zeit und Muße hab, schau ich mir das irgendwann an. Beides ist neben Job und einjährigen Zwillingen aber etwas Mangelware.

**Comment by AlCalzone** [comment]
Geräte sind angekommen, heute ist `npm` aber nicht willig und hängt seit 1h immer wieder. D.h. leider kein Fortschritt...
