### ISSUE TITLE
upgrade 0.13.3 auf 0.13.4 npm ERR

### ISSUE THREAD

**Issue by crunchip77** [AlCalzone/ioBroker.ble#801]
`<html>
<body>

host.IoBroker | 2023-07-08 21:48:59.446 | info | iobroker exit 0
-- | -- | -- | --
host.IoBroker | 2023-07-08 21:48:58.374 | info | iobroker upload [0] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/style.css style.css text/css
host.IoBroker | 2023-07-08 21:48:58.336 | info | iobroker upload [1] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/index_m.html index_m.html text/html
host.IoBroker | 2023-07-08 21:48:58.145 | info | iobroker upload [2] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/build/index.js.map build/index.js.map application/json
host.IoBroker | 2023-07-08 21:48:58.097 | info | iobroker upload [3] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/build/index.js build/index.js application/javascript
host.IoBroker | 2023-07-08 21:48:58.083 | info | iobroker upload [4] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/ble.png ble.png image/png
host.IoBroker | 2023-07-08 21:48:58.038 | info | iobroker upload [5] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/.eslintrc.js .eslintrc.js application/javascript
host.IoBroker | 2023-07-08 21:48:54.114 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-07-08T19_48_38_497Z-debug-0.log
host.IoBroker | 2023-07-08 21:48:54.111 | info | iobroker npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noblenpm ERR! gyp ERR! node -v v18.16.0npm ERR! gyp ERR! node-gyp -v v7.1.2npm ERR! gyp ERR! not ok
host.IoBroker | 2023-07-08 21:48:54.108 | info | iobroker npm ERR! ^^^^^^^^^^^^^^^^^npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_mainnpm ERR! return main(sys.argv[1:])npm ERR! ^^^^^^^^^^^^^^^^^^npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in mainnpm ERR! return gyp_main(args)npm ERR! ^^^^^^^^^^^^^^npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_mainnpm ERR! [generator, flat_list, targets, data] = Load(npm ERR! ^^^^^npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Loadnpm ERR! result = gyp.input.Load(npm ERR! ^^^^^^^^^^^^^^^npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Loadnpm ERR! LoadTargetBuildFile(npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFilenpm ERR! build_file_data = LoadOneBuildFile(npm ERR! ^^^^^^^^^^^^^^^^^npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFilenpm ERR! build_file_contents = open(build_file_path, "rU").read()npm ERR! ^^^^^^^^^^^^^^^^^^^^^^^^^^^npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gypnpm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1npm ERR! gyp ERR! stack at ChildProcess.onCpExit (/opt/iobroker/node_modules/node-gyp/lib/configure.js:351:16)npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12)npm ERR! gyp ERR! System Linux 6.1.0-9-amd64
host.IoBroker | 2023-07-08 21:48:54.104 | info | iobroker npm ERR! gyp info spawn args [npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',npm ERR! gyp info spawn args 'binding.gyp',npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/home/iobroker/.cache/node-gyp/18.16.0/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.16.0',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! Traceback (most recent call last):npm ERR! File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>npm ERR! sys.exit(gyp.script_main())
host.IoBroker | 2023-07-08 21:48:54.102 | info | iobroker npm ERR! command sh -c node-gyp-buildnpm ERR! gyp info it worked if it ends with oknpm ERR! gyp info using node-gyp@7.1.2npm ERR! gyp info using node@18.16.0 \| linux \| x64npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"npm ERR! (node:3719470) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)npm ERR! gyp info spawn /usr/bin/python3
host.IoBroker | 2023-07-08 21:48:54.100 | info | iobroker npm ERR! command failed
host.IoBroker | 2023-07-08 21:48:54.097 | info | iobroker npm ERR! code 1npm ERR! path /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
host.IoBroker | 2023-07-08 21:48:37.715 | info | iobroker Installing iobroker.ble@0.13.4... (System call)
host.IoBroker | 2023-07-08 21:48:37.714 | info | iobroker NPM version: 9.5.1
host.IoBroker | 2023-07-08 21:48:36.789 | info | iobroker Update ble from @0.13.3 to @0.13.4
host.IoBroker | 2023-07-08 21:48:34.076 | info | iobroker upgrade ble@0.13.4 --debug

</body>
</html>`

Debian VM
Node.js version
18.16.0
NPM version
9.5.1

**Comment by crunchip77** [comment]
ein Versuch den Adapter neu zu installieren sie ebenfalls so aus
`root@IoBroker:~# iob add ble --debug
NPM version: 9.5.1
Installing iobroker.ble@0.13.4... (System call)
npm ERR! code 1
npm ERR! path /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.16.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! (node:519398) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/iobroker/.cache/node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/opt/iobroker/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 6.1.0-10-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2023-07-27T05_19_09_872Z-debug-0.log
npm ERR! code 1
npm ERR! path /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.16.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! (node:519398) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/iobroker/.cache/node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/opt/iobroker/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 6.1.0-10-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2023-07-27T05_19_09_872Z-debug-0.log
host.IoBroker Cannot install iobroker.ble@0.13.4: 1
`

**Comment by crunchip77** [comment]
v 0.13.3 lässt sich hingegen problemlos installieren

**Comment by crunchip77** [comment]
ok, seh ich mir an, danke erstmal für die Info

**Comment by crunchip77** [comment]
Anmerkung noch, hatte ich oben vergessen, debian bookworm

ich habe jetzt folgendes probiert,
* apt install --reinstall nodejs, ohne Erfolg
* /opt/iobroker/node_modules/iobroker.ble# npm install --omit=dev
`npm ERR! code 1
npm ERR! path /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.17.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! (node:362741) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/opt/iobroker/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/iobroker/.cache/node-gyp/18.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/opt/iobroker/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 6.1.0-10-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/iobroker.ble/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v18.17.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
`
* und ein cd /opt/iobroker
npm prune, ohne Erfolg

**Comment by AlCalzone** [comment]
Ich kann leider keinen Support für verbogene node/npm-Installationen liefern. Bitte probier's damit im ioBroker Forum.

**Comment by crunchip77** [comment]
Wüsste zwar nicht was da verbogen ist aber werde mal das Forum dazu befragen. Ansonsten lass ich die 0.13.3 weiter laufen.
Danke dir erstmal

**Comment by AlCalzone** [comment]
Wenn module nach der Installation nicht gefunden werden können, ist das immer ein gutes Zeichen dafür, dass da was verpfuscht ist.
Der Adapter kann da nicht viel ausrichten.

**Comment by crunchip77** [comment]
Das mag ja sein, es wurde aber eine saubere neue iobroker  installation incl nodejs v16 gemacht. Danach nur die regulären update's und nodejs auf 18 angehoben.

Zwischenzeitlich debian auf bookworm umgestellt.
Bisher gab es nirgends irgend welche Probleme.

Ich wüsste wirklich nicht wo da was krum wäre und es macht  auch nur die 0.13.4 ein Problem.
Die 0.13.3 lässt sich ja Problemlos installieren.

Reine Vermutung meinerseits, entweder liegt das Problem bei v18 oder in Konstellation mit bookworm.

Aber ich bin dran im Forum, eventuell liegt es an 
/usr/lib/python3.11/EXTERNALLY-MANAGED

**Comment by crunchip77** [comment]
ich habe nun in
/opt/iobroker/node_modules/node-gyp/gyp/pylib/gyp/input.py
die folgenden Zeile von
build_file_contents = open(build_file_path, 'rU').read()
in
build_file_contents = open(build_file_path, 'r').read()
geändert.
siehe https://github.com/nodejs/node-gyp/issues/2219#issuecomment-1406630954
