### ISSUE TITLE
Hohe CPU Last 

### ISSUE THREAD

**Issue by haahne** [AlCalzone/ioBroker.ble#808]
Hallo :) 
Installiert ist Version 0.13.4
Überwacht werden 7 FlowerCare Sensoren + 1 Xiaomi Thermometer.
Wenn ich mir die CPU Auslastung mit "top" anzeigen lassen steht der ble Adapter bei mir ganz oben mit ca. 15%.
Normal oder zuviele Geräte?

**Comment by AlCalzone** [comment]
Magst du mal logs auf Level "debug" machen und ne Minute laufen lassen dass ich sehe wie viel da rein kommt?

**Comment by haahne** [comment]
[ble.debug.txt](https://github.com/AlCalzone/ioBroker.ble/files/12207692/ble.debug.txt)

Jetzt ca. 1 Minute und 1MB groß kommt schon viel rein.

**Comment by AlCalzone** [comment]
Ja, da gibts doch einige, die immer wieder das gleiche senden. Ggf. lässt sich da was optimieren, dass nicht bei jedem Paket alle paar 100ms die ioBroker-Objekte aktualisiert werden.

Wäre nur die Frage, ob du ggf. zu viele uninteressante Objekte "aktiv" hast. Z.B. `e8:e7:31:f8:be:a0`, sendet sehr häufig unter Service `fd3d` die gleichen Daten. Wertest du die ggf. per Skript aus, oder ist das einfach eins was zufällig mit gefunden wurde?
Dann könnte es sich lohnen das zugehörige Device zu löschen.

**Comment by haahne** [comment]
![image](https://github.com/AlCalzone/ioBroker.ble/assets/120421080/2f1a7db4-f0bc-4d52-9e6e-d89e1dcaa3f1)
Mit dieser MAC habe ich gar kein Device. Ich lösche nach dem Scannen immer alle mir unbekannten Objekte.

**Comment by AlCalzone** [comment]
Welche plug-ins und services hast du aktiv für den Scan? Siehe Einstellungen?

**Comment by haahne** [comment]
![settings](https://github.com/AlCalzone/ioBroker.ble/assets/120421080/1c438117-6f15-47ad-9e51-791f783b370e)

Log gibt ca. einmal am Tag Folgende Error's:

2023-07-30 14:57:50.615 - error: ble.0 (17566) The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5
2023-07-30 16:02:43.825 - error: ble.0 (17566) The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5
2023-07-30 16:02:44.118 - error: ble.0 (17566) The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4

Wochtig ? Extra Issue aufmachen?
