### ISSUE TITLE
The value of "offset" is out of range. It must be >= 0 and <= 23. Received 24

### ISSUE THREAD

**Issue by haahne** [AlCalzone/ioBroker.ble#823]
Bekomme mehrmals am Tag folgende Error's : 

ble.0 |2023-12-02 17:02:58.983 | error | The value of "offset" is out of range. It must be >= 0 and <= 23. Received 24
ble.0 | 2023-12-02 10:22:58.190 | error | The value of "offset" is out of range. It must be >= 0 and <= 10. Received 12
ble.0 | 2023-12-02 05:14:57.726 | error | The value of "offset" is out of range. It must be >= 0 and <= 23. Received 24
ble.0 | 2023-12-02 01:20:27.190 | error | The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4

Kann es daran liegen das ich Parallel den Radar2 Adapter laufen lasse? Der Scannt nach BLE Beacons .
Habe schonmal versucht 2 BT Sticks Parallel auf einem System laufen zu lassen , funktioniert garnicht auch wenn jeder Instanz ein eigener BT Stick zugewiesen ist. Darum nutzen beide Adapter jetzt einen Stick. 
Gibt es irgendwo die Möglichkeit den Offset Wert einzustellen?
Grüße

**Comment by AlCalzone** [comment]
AFAIK ist das ein Fehler aus der zugrundeliegenden Bluetooth-Library.
